# .readthedocs.yaml

version: 2

# Set the OS and build tools (Python)
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Use Sphinx to build the documentation
sphinx:
  configuration: docs/conf.py  # Adjust if your conf.py is in a different folder

# Install dependencies
python:
  install:
    - requirements: docs/requirements.txt  # Ensure this file exists
